### ISSUE TITLE
filters.eq

### ISSUE THREAD

**Issue by Fabszn** [zeal18/zio-mongodb#171]
Hello,

I am trying to use zio-mongodb. 
I am facing with an issue. 

when I try to used 'filters.eq' it seems that scala eq() method is used instead of eq() from filters object. 

where I am wrong?

**Comment by zeal18** [comment]
Hi! I'll check it a bit later. As a workaround I can suggest to import the 'filters' object instead and call the method from there like 'filters.eq'

**Comment by Fabszn** [comment]
I tested with import but same result

**Comment by Fabszn** [comment]
It is not open-source project. 
I will prepare an example to show you the issue

**Comment by zeal18** [comment]
Hey @Fabszn! Do you still face the issue?
