### ISSUE TITLE
How to perform transactions

### ISSUE THREAD

**Issue by signalfrax** [zeal18/zio-mongodb#204]
After reading the [official mongo docs](https://www.mongodb.com/docs/manual/core/transactions/) and looking around in the zio-mongodb code I came up with the following sample code. Is it correct?

```scala

case class Sample(...)

case class Sample2(...)

val db = mongoDB
      .withReadPreference(ReadPreference.primary())
      .withReadConcern(ReadConcern.SNAPSHOT)
      .withWriteConcern(WriteConcern.MAJORITY)

    val sampleCollection = db.getCollection[Sample]("sample_collection")
    val sample2Collection = db.getCollection[Sample2]("sample2_collection")

    ZIO.scoped {
      for {
        session               <- db.startSession()
        _                         <- ZIO.succeed(session.startTransaction())
        _                         <- sampleCollection.deleteOne(session, filters.eq("someid"))
        _                         <- sample2Collection.deleteOne(session, filters.eq("someid"))
        _                         <- ZIO.succeed(session.commitTransaction())
      } yield ()
    }
  }

```

**Comment by zeal18** [comment]
Hi @signalfrax!
Generally, your code looks fine, but I'm not sure if you need to start and commit the transaction explicitly. 
I'm on a little vacation at the moment and will be able to check it next week

**Comment by zeal18** [comment]
Hi @signalfrax! I checked docs: it seems one should start a transaction and commit it explicitly, so your code is totally correct

Looking at the code example, I don't like how it looks, especially `ZIO.succeed(session.startTransaction())` lines, I'll think about better dsl... or you can try to make one and create a PR ☺️

**Comment by signalfrax** [comment]
Hey @zeal18!  Thank you for looking into this!. I will definitely open a PR. I have a couple of other things such as the `$merge` functionality that I want to contribute to this project. Will keep you posted.

**Comment by zeal18** [comment]
@signalfrax sounds great, thank you! Regarding the `$merge` aggregation stage, take a look at my "in progress" PR: https://github.com/zeal18/zio-mongodb/pull/190 . I started adding more aggregation stages there which ended up introducing the `Expression` model.
The PR doesn't implement everything I wanted to implement there, but it grew too big and I'm going to merge it as is. I'm bringing it to your attention as there you can find commits which can be an example of adding a new aggregation step and testing it properly (for example, this commit can help: https://github.com/zeal18/zio-mongodb/pull/190/commits/495972a4d6d7669cb68eab26505d79b6896ff7eb)

I'm closing the issue as it's solved, feel free to open a new one if needed

**Comment by signalfrax** [comment]
Here's a complete example on how to do transactions using zio-mongodb. I'll create a PR with a better DSL later. You need to use the [interop-reactive-streams](https://github.com/zio/interop-reactive-streams) because the underlying scala mongodb driver makes use of Reactive streams when doing transactions.

```scala
import zio._
import zio.interop.reactivestreams._
import zio.stream._

case class Sample(...)

case class Sample2(...)

val db = mongoDB
      .withReadPreference(ReadPreference.primary())
      .withReadConcern(ReadConcern.SNAPSHOT)
      .withWriteConcern(WriteConcern.MAJORITY)

    val sampleCollection = db.getCollection[Sample]("sample_collection")
    val sample2Collection = db.getCollection[Sample2]("sample2_collection")

    ZIO.scoped {
      for {
        session               <- db.startSession()
        _                         = session.startTransaction()
        _                         <- sampleCollection.deleteOne(session, filters.eq("someid"))
        _                         <- sample2Collection.deleteOne(session, filters.eq("someid"))
        _                         <- session.commitTransaction().toZIOStream(2).runDrain
      } yield ()
    }
  }
```

> The `qSize` parameter for `toZIOStream` needs to be at least 2 otherwise an Assertion exception is thrown. 

> The mongoDB value is an instance of `MongoDatabase`
