### ISSUE TITLE
Codec Derivation

### ISSUE THREAD

**Issue by Executioner1939** [zeal18/zio-mongodb#70]
Hi,

Firstly, thank you for the massive effort you have put into this, it solves almost all issues with the current Scala and Java Drivers.

I am currently trying to simply insert a case class, but am getting a NPE while doing so. I have tried to read through the test cases to see what I may need to do to setup the driver correctly and I believe I have done so. 

I added a `Codec[UUID]` as below:
```scala
implicit val uid: Codec[UUID] = Codec[String].bimap(str => UUID.fromString(str), (id: UUID) => id.toString)
```

as that was preventing compilation, however I am still getting an error, I know that my case class does have a custom type as is below:

```scala
object DocumentTypes {
  type DocumentType = String
}
```
It is also quite nested along with a List.

Here is the error:
```scala
timestamp=2022-10-12T10:21:15.7951366+02:0 level=ERROR thread=zio-fiber-31 message="Error Inserting" cause=Exception in thread "zio-fiber-" java.lang.NullPointerException: null
	at io.github.zeal18.zio.mongodb.bson.codecs.MagnoliaCodec$InlinedCaseClassCodec.$anonfun$encode$3(MagnoliaCodec.scala:115)
```

Any help with this would be appreciated

**Comment by Executioner1939** [comment]
I moved my UUID Codec out into a separate object and it seems to work, sorry for this 👍🏻

**Comment by zeal18** [comment]
Hi @Executioner1939! No worries and thank you for reaching me out. It looks like a bug in magnolia, it would be nice if your could provide a simple reproducible example, I would like to investigate the problem a bit deeper

**Comment by Executioner1939** [comment]
Hi @zeal18 thanks for the response :-).

The below isn't a full example, but is what I did.

```scala
case class UserVerificationRepository(database: MongoDatabase, tracing: Tracing) {
  private val COLLECTION_NAME: String = "user.verification"
  private val COLLECTION: MongoCollection[Enrollment] = database.getCollection[Enrollment](COLLECTION_NAME)

  implicit val uid: Codec[UUID] = Codec[String].bimap(str => UUID.fromString(str), (id: UUID) => id.toString)

  ...rest of class
}
```

I added the `Codec` as above as I was testing, and the app compiled, but failed at Runtime. Hopefully this helps :-).
